config/routes.rb
Nutrition::Engine.routes.draw do
  resources :masses
  resources :nutrient_values
  resources :foods
  resources :langual_factors
  resources :nutrients
  resources :food_groups
end

app/models/nutrition/food.rb
module Nutrition
  class Food < ActiveRecord::Base
    belongs_to :food_group
    has_many :masses, :foreign_key => :nutrition_food_id
    has_and_belongs_to_many :langual_factors
  end
end

app/models/nutrition/food_group.rb
module Nutrition
  class FoodGroup < ActiveRecord::Base
  end
end

app/models/nutrition/langual_factor.rb
module Nutrition
  class LangualFactor < ActiveRecord::Base
    has_and_belongs_to_many :foods
  end
end

app/models/nutrition/mass.rb
module Nutrition
  class Mass < ActiveRecord::Base
    belongs_to :food, :foreign_key => :nutrition_food_id
  end
end

app/models/nutrition/nutrient.rb
module Nutrition
  class Nutrient < ActiveRecord::Base
    has_many :nutrition_nutrient_values
    has_many :foods, :through => :nutrition_nutrient_values
  end
end

app/models/nutrition/nutrient_value.rb
module Nutrition
  class NutrientValue < ActiveRecord::Base
    belongs_to :food
    belongs_to :nutrient
  end
end

app/controllers/nutrition/application_controller.rb
module Nutrition
  class ApplicationController < ActionController::Base
  end
end

app/controllers/nutrition/food_groups_controller.rb
require_dependency "nutrition/application_controller"

module Nutrition
  class FoodGroupsController < ApplicationController
    before_action :set_food_group, only: [:show, :edit, :update, :destroy]

    # GET /food_groups
    def index
      @food_groups = FoodGroup.all
    end

    # GET /food_groups/1
    def show
    end

    # GET /food_groups/new
    def new
      @food_group = FoodGroup.new
    end

    # GET /food_groups/1/edit
    def edit
    end

    # POST /food_groups
    def create
      @food_group = FoodGroup.new(food_group_params)

      if @food_group.save
        redirect_to @food_group, notice: 'Food group was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /food_groups/1
    def update
      if @food_group.update(food_group_params)
        redirect_to @food_group, notice: 'Food group was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /food_groups/1
    def destroy
      @food_group.destroy
      redirect_to food_groups_url, notice: 'Food group was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_food_group
        @food_group = FoodGroup.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def food_group_params
        params.require(:food_group).permit(:name)
      end
  end
end

app/controllers/nutrition/foods_controller.rb
require_dependency "nutrition/application_controller"

module Nutrition
  class FoodsController < ApplicationController
    before_action :set_food, only: [:show, :edit, :update, :destroy]

    # GET /foods
    def index
      @foods = Food.all
    end

    # GET /foods/1
    def show
    end

    # GET /foods/new
    def new
      @food = Food.new
    end

    # GET /foods/1/edit
    def edit
    end

    # POST /foods
    def create
      @food = Food.new(food_params)

      if @food.save
        redirect_to @food, notice: 'Food was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /foods/1
    def update
      if @food.update(food_params)
        redirect_to @food, notice: 'Food was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /foods/1
    def destroy
      @food.destroy
      redirect_to foods_url, notice: 'Food was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_food
        @food = Food.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def food_params
        params.require(:food).permit(:food_group_id, :description, :summary, :aliases, :manufacturer, :is_complete, :waste_description, :waste_yield, :origin, :nitrogen_protein_yield, :protein_calorie_yield, :fat_calorie_yield, :carb_calorie_yield)
      end
  end
end

app/controllers/nutrition/langual_factors_controller.rb
require_dependency "nutrition/application_controller"

module Nutrition
  class LangualFactorsController < ApplicationController
    before_action :set_langual_factor, only: [:show, :edit, :update, :destroy]

    # GET /langual_factors
    def index
      @langual_factors = LangualFactor.all
    end

    # GET /langual_factors/1
    def show
    end

    # GET /langual_factors/new
    def new
      @langual_factor = LangualFactor.new
    end

    # GET /langual_factors/1/edit
    def edit
    end

    # POST /langual_factors
    def create
      @langual_factor = LangualFactor.new(langual_factor_params)

      if @langual_factor.save
        redirect_to @langual_factor, notice: 'Langual factor was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /langual_factors/1
    def update
      if @langual_factor.update(langual_factor_params)
        redirect_to @langual_factor, notice: 'Langual factor was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /langual_factors/1
    def destroy
      @langual_factor.destroy
      redirect_to langual_factors_url, notice: 'Langual factor was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_langual_factor
        @langual_factor = LangualFactor.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def langual_factor_params
        params.require(:langual_factor).permit(:description)
      end
  end
end

app/controllers/nutrition/masses_controller.rb
require_dependency "nutrition/application_controller"

module Nutrition
  class MassesController < ApplicationController
    before_action :set_mass, only: [:show, :edit, :update, :destroy]

    # GET /masses
    def index
      @masses = Mass.all
    end

    # GET /masses/1
    def show
    end

    # GET /masses/new
    def new
      @mass = Mass.new
    end

    # GET /masses/1/edit
    def edit
    end

    # POST /masses
    def create
      @mass = Mass.new(mass_params)

      if @mass.save
        redirect_to @mass, notice: 'Mass was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /masses/1
    def update
      if @mass.update(mass_params)
        redirect_to @mass, notice: 'Mass was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /masses/1
    def destroy
      @mass.destroy
      redirect_to masses_url, notice: 'Mass was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_mass
        @mass = Mass.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def mass_params
        params.require(:mass).permit(:food_id, :seq, :quantity, :unit, :mass, :datapoints, :standard_deviation)
      end
  end
end

app/controllers/nutrition/nutrient_values_controller.rb
require_dependency "nutrition/application_controller"

module Nutrition
  class NutrientValuesController < ApplicationController
    before_action :set_nutrient_value, only: [:show, :edit, :update, :destroy]

    # GET /nutrient_values
    def index
      @nutrient_values = NutrientValue.all
    end

    # GET /nutrient_values/1
    def show
    end

    # GET /nutrient_values/new
    def new
      @nutrient_value = NutrientValue.new
    end

    # GET /nutrient_values/1/edit
    def edit
    end

    # POST /nutrient_values
    def create
      @nutrient_value = NutrientValue.new(nutrient_value_params)

      if @nutrient_value.save
        redirect_to @nutrient_value, notice: 'Nutrient value was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /nutrient_values/1
    def update
      if @nutrient_value.update(nutrient_value_params)
        redirect_to @nutrient_value, notice: 'Nutrient value was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /nutrient_values/1
    def destroy
      @nutrient_value.destroy
      redirect_to nutrient_values_url, notice: 'Nutrient value was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_nutrient_value
        @nutrient_value = NutrientValue.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def nutrient_value_params
        params.require(:nutrient_value).permit(:food_id, :nutrient_id, :yield, :is_fortified, :estimated_from, :last_update)
      end
  end
end

app/controllers/nutrition/nutrients_controller.rb
require_dependency "nutrition/application_controller"

module Nutrition
  class NutrientsController < ApplicationController
    before_action :set_nutrient, only: [:show, :edit, :update, :destroy]

    # GET /nutrients
    def index
      @nutrients = Nutrient.all
    end

    # GET /nutrients/1
    def show
    end

    # GET /nutrients/new
    def new
      @nutrient = Nutrient.new
    end

    # GET /nutrients/1/edit
    def edit
    end

    # POST /nutrients
    def create
      @nutrient = Nutrient.new(nutrient_params)

      if @nutrient.save
        redirect_to @nutrient, notice: 'Nutrient was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /nutrients/1
    def update
      if @nutrient.update(nutrient_params)
        redirect_to @nutrient, notice: 'Nutrient was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /nutrients/1
    def destroy
      @nutrient.destroy
      redirect_to nutrients_url, notice: 'Nutrient was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_nutrient
        @nutrient = Nutrient.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def nutrient_params
        params.require(:nutrient).permit(:unit, :label, :name, :significant_figures, :position)
      end
  end
end

app/helpers/nutrition/application_helper.rb
module Nutrition
  module ApplicationHelper
  end
end

app/helpers/nutrition/food_groups_helper.rb
module Nutrition
  module FoodGroupsHelper
  end
end

app/helpers/nutrition/foods_helper.rb
module Nutrition
  module FoodsHelper
  end
end

app/helpers/nutrition/langual_factors_helper.rb
module Nutrition
  module LangualFactorsHelper
  end
end

app/helpers/nutrition/masses_helper.rb
module Nutrition
  module MassesHelper
  end
end

app/helpers/nutrition/nutrient_values_helper.rb
module Nutrition
  module NutrientValuesHelper
  end
end

app/helpers/nutrition/nutrients_helper.rb
module Nutrition
  module NutrientsHelper
  end
end

app/views/nutrition/nutrient_values/_form.html.erb
<%= form_for(@nutrient_value) do |f| %>
  <% if @nutrient_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nutrient_value.errors.count, "error") %> prohibited this nutrient_value from being saved:</h2>

      <ul>
      <% @nutrient_value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.text_field :food_id %>
  </div>
  <div class="field">
    <%= f.label :nutrient_id %><br>
    <%= f.text_field :nutrient_id %>
  </div>
  <div class="field">
    <%= f.label :yield %><br>
    <%= f.text_field :yield %>
  </div>
  <div class="field">
    <%= f.label :is_fortified %><br>
    <%= f.check_box :is_fortified %>
  </div>
  <div class="field">
    <%= f.label :estimated_from %><br>
    <%= f.number_field :estimated_from %>
  </div>
  <div class="field">
    <%= f.label :last_update %><br>
    <%= f.datetime_select :last_update %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nutrition/nutrient_values/edit.html.erb
<h1>Editing Nutrient Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @nutrient_value %> |
<%= link_to 'Back', nutrient_values_path %>

app/views/nutrition/nutrient_values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Nutrient Values</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Nutrient</th>
      <th>Yield</th>
      <th>Is fortified</th>
      <th>Estimated from</th>
      <th>Last update</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nutrient_values.each do |nutrient_value| %>
      <tr>
        <td><%= nutrient_value.food %></td>
        <td><%= nutrient_value.nutrient %></td>
        <td><%= nutrient_value.yield %></td>
        <td><%= nutrient_value.is_fortified %></td>
        <td><%= nutrient_value.estimated_from %></td>
        <td><%= nutrient_value.last_update %></td>
        <td><%= link_to 'Show', nutrient_value %></td>
        <td><%= link_to 'Edit', edit_nutrient_value_path(nutrient_value) %></td>
        <td><%= link_to 'Destroy', nutrient_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nutrient value', new_nutrient_value_path %>

app/views/nutrition/nutrient_values/new.html.erb
<h1>New Nutrient Value</h1>

<%= render 'form' %>

<%= link_to 'Back', nutrient_values_path %>

app/views/nutrition/nutrient_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @nutrient_value.food %>
</p>

<p>
  <strong>Nutrient:</strong>
  <%= @nutrient_value.nutrient %>
</p>

<p>
  <strong>Yield:</strong>
  <%= @nutrient_value.yield %>
</p>

<p>
  <strong>Is fortified:</strong>
  <%= @nutrient_value.is_fortified %>
</p>

<p>
  <strong>Estimated from:</strong>
  <%= @nutrient_value.estimated_from %>
</p>

<p>
  <strong>Last update:</strong>
  <%= @nutrient_value.last_update %>
</p>

<%= link_to 'Edit', edit_nutrient_value_path(@nutrient_value) %> |
<%= link_to 'Back', nutrient_values_path %>